; Spacing configurations for the mesh generation
[Spacing]
hmax = 30.0 
; Maximum spacing in kilometers
hshr = 4.0 
; Spacing at the shoreline in kilometers
nwav = -200
; Number of cells per square root of (gravity * water depth), 140 gives H**1/2 spacing
; negative values turn off spacin
; really this is number of cells per M2 wavelength
hmin = 4.0 
; Minimum spacing in kilometers
dhdx = 0.30
; Maximum allowable gradient in spacing
hcenter = 150
; center depth for tanh spacing. set to <0 to turn off
hbeta = 0.01 
; stretching factor for tanh spacing

; Mesh generation settings
[MeshSettings]
;arctic_hmin_lat = 90
;; set a limit to ensure hmin is at pole
arctic_hmax_lat = 86
arctic_hmax_val = 50
hfun_hmax = 35
hfun_hmin = 1
; Global maximum mesh resolution, similar to hmax
;mesh_file = ./data/25km_to_3km_g30_nwav200_50kmN86.msh
mesh_file = ./data/30km_to_4km_tanh_h0150_hb001_scl_50kmN86_landmask_1m.msh
; Filename for the generated mesh in Jigsaw format
;ww3_mesh_file = ./data/25km_to_3km_g30_nwav200_50kmN86.ww3 
ww3_mesh_file = ./data/30km_to_4km_tanh_h0150_hb001_scl_50kmN86_landmask_1m.ww3
; Filename for the mesh in WW3 format

; Command-line arguments and their default values
[CommandLineArgs]
black_sea = 1 
;arctic_lim = 90
; default value for arctic_lim is 90
; Black Sea configuration mode: 1=no Black Sea, 2=detached, 3=connected
;mask_file = ./data/wmask_25km_to_3km_g30_nwav200_50kmN86.nc 
mask_file = ./data/wmask_30km_to_4km_tanh_h0150_hb001_scl_50kmN86_15s.nc 
; Path to the weighting mask file, if any

; Bathymetry and Regional data
[DataFiles]
dem_file = /home/gsu000/data/ppp7/GEBCO/GEBCO_2026_staggered.nc
#dem_file = /home/gsu000/projects/WW3-tools/unst_msh_gen/RTopo_2_0_4_GEBCO_v2023_60sec_pixel.nc
; DEM file

