; Spacing configurations for the mesh generation
[Spacing]
hmax = 50 
; Maximum spacing in kilometers
hshr = 1 
; Spacing at the shoreline in kilometers
nwav = -200
; Number of cells per square root of (gravity * water depth), 140 gives H**1/2 spacing
; negative values turn off spacin
; really this is number of cells per M2 wavelength
hmin = 1 
; Minimum spacing in kilometers
dhdx = 0.2
; Maximum allowable gradient in spacing
hcenter = 50
; center depth for tanh spacing. set to <0 to turn off
hbeta = 0.02
; stretching factor for tanh spacing

; Mesh generation settings
[MeshSettings]
;; set a limit to ensure hmin is at pole
arctic_hmax_lat = 88
arctic_hmax_val = 40
hfun_hmax = 50
hfun_hmin = 1
mesh_file = ./data/50km_to_1km_tanh_h050_hb0.02_landmask_1m_dhdx0.2_40m88N.msh
; Filename for the generated mesh in Jigsaw format
ww3_mesh_file = ./data/50km_to_1km_tanh_h050_hb0.02_landmask_1m_dhdx0.2_40m88N.ww3

; Command-line arguments and their default values
[CommandLineArgs]
; default value for arctic_lim is 90
mask_file = ./data/50km_to_1km_tanh_h050_hb0.02_landmask_1m_dhdx0.2_40m88N.nc
; Path to the weighting mask file, if any

; Bathymetry and Regional data
[DataFiles]
; DEM file
dem_file = /home/gsu000/projects/WW3-tools/unst_msh_gen/RTopo_2_0_4_GEBCO_v2023_60sec_pixel.nc
