; Spacing configurations for the mesh generation
[Spacing]
hmax = 25.0 
; Maximum spacing in kilometers
hshr = 10.0 
; Spacing at the shoreline in kilometers
nwav = 300
; Number of cells per square root of (gravity * water depth), 140 gives H**1/2 spacing
; negative values turn off spacin
; really this is number of cells per M2 wavelength
hmin = 10.0 
; Minimum spacing in kilometers
dhdx = 0.10
; Maximum allowable gradient in spacing

; Mesh generation settings
[MeshSettings]
;arctic_hmin_lat = 90
;; set a limit to ensure hmin is at pole
arctic_hmax_lat = 86
arctic_hmax_val = 50
hfun_hmax = 25
hfun_hmin = 10
; Global maximum mesh resolution, similar to hmax
mesh_file = ./data/25km_to_10km_g10_nwav300_50kmN86.msh
; Filename for the generated mesh in Jigsaw format
ww3_mesh_file = ./data/25km_to_10km_g10_nwav300_50kmN86.ww3 
; Filename for the mesh in WW3 format

; Command-line arguments and their default values
[CommandLineArgs]
black_sea = 3 
;arctic_lim = 90
; default value for arctic_lim is 90
; Black Sea configuration mode: 1=no Black Sea, 2=detached, 3=connected
mask_file = ./data/wmask_25km_to_10km_g10_nwav300_50kmN86.nc 
; Path to the weighting mask file, if any

; Bathymetry and Regional data
[DataFiles]
dem_file = /home/gsu000/p/WW3-tools/unst_msh_gen/RTopo_2_0_4_GEBCO_v2023_60sec_pixel.nc
; DEM file

;shape_file = [{"path": "/scratch1/NCEPDEV/stmp2/Ali.Salimi/msh-gen/unst_msh_gen/VAR-MESH/Shapefiles/Arctic.shp", "scale": 10}, {"path": "/scratch1/NCEPDEV/stmp2/Ali.Salimi/msh-gen/unst_msh_gen/VAR-MESH/Shapefiles/Gulf.shp", "scale": 5}, {"path": "/scratch1/NCEPDEV/stmp2/Ali.Salimi/msh-gen/unst_msh_gen/VAR-MESH/Shapefiles/Hawaii.shp", "scale": 5}, {"path": "/scratch1/NCEPDEV/stmp2/Ali.Salimi/msh-gen/unst_msh_gen/VAR-MESH/Shapefiles/PurtoRico.shp", "scale": 10}, {"path": "/scratch1/NCEPDEV/stmp2/Ali.Salimi/msh-gen/unst_msh_gen/VAR-MESH/Shapefiles/WestCoast.shp", "scale": 5}]
;shape_file = [{"path":"./boundary_coords_nwa.shp", "scale": 5}, {"path":"./boundary_coords_nep.shp", "scale":5}]
; shapefiles for regional mesh tefinement
;gaussian_file = [{"radius": 6371, "lon0":-97, "lat0":75, "sigma":3000, "hmax":25, "hmin":5}, {"radius":6371, "lon0":-126.0, "lat0":50.0, "sigma":700, "hmax":5, "hmin":2}, {"radius":6371, "lon0":-59.0, "lat0":49.0, "sigma":700, "hmax":5, "hmin":2}]
; gaussian for regional mesh refinement

;window_file = [{"min_lon":-180, "max_lon":180, "min_lat":67, "max_lat":90, "hshr":5}, {"min_lon":-180, "max_lon":-40, "min_lat":27, "max_lat":67", "hshr":5}]
;window_file = [{"min_lon": -98, "max_lon": -64, "min_lat": 24, "max_lat": 44.5, "hshr": 5}, {"min_lon": -158, "max_lon": -155, "min_lat": 19, "max_lat": 22, "hshr": 5}, {"min_lon": -128, "max_lon": -64, "min_lat": 34.5, "max_lat": 48.5, "hshr": 5}, {"min_lon": -67.4, "max_lon": -64.1, "min_lat": 17.2, "max_lat": 18.3, "hshr": 5}]
; user-defined windows to refine the mesh regionally.
;window_file = [{"min_lon": -170, "max_lon": -42, "min_lat": 31, "max_lat": 84, "hmin": 5, "hmax": 25, "nwav": 300}]
;window_file = [{"min_lon": -157, "max_lon": -120, "min_lat": 40, "max_lat": 84, "hmin": 5, "hmax": 25, "nwav": 300}, {"min_lon": -120, "max_lon": -42, "min_lat": 31, "max_lat": 84, "hmin": 5, "hmax": 25, "nwav": 300}]
;, {"min_lon": -180, "max_lon": -40, "min_lat": 27, "max_lat": 67, "hmin": 5, "hmax": 25, "nwav": 200}]
;window_file = [{"min_lon": -180., "max_lon": 180., "min_lat": 27, "max_lat": 86, "hmin": 5., "hmax": 25., "nwav":200}]
